config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Opis") %>
<h1>Opis</h1>
<p>
  Spletna aplikacija Tvidter je simulacija socialnega omrežja Twitter, ustvarjena v ogrodju Ruby on Rails, z namenom
  predstavitve mojih sposobnosti razvijanja spletnih aplikacij. Avtor: <a href="http://vido.si">Vid Jerčič</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Kontakt</h1>
<p>
 Kontaktiraj me preko 
  <a href="http://vido.si/contacts">moje spletne strani</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Pomoč</h1>
<p>
  <a href="vido.si">Ruby on Rails aplikacija</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      

      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Objave:</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Dobrodošli na Tvidterju</h1>
      <h2>
      Pridruži se novemu socialnemu omrežju
    </h2>
    <%= link_to "Registriraj se!", signup_path, class: "btn btn-lg btn-primary" %>
<% end %>