config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  

  root 'static_pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Obrazec vsebuje napake!  <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: {multipart: true}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Ustvari novo objavo..." %>
  </div>
  <%= f.submit "Objavi", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, placeholder: "slika", accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Največja dovoljena velikost je 5MB. Prosim izberi manjšo datoteko.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    sledi
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    sledilci
  </a>
</div>

app/views/shared/_user_info.html.erb
<div class="twPc-div">


	<div>

      <%= link_to gravatar_for(current_user, size: 50), class: "twPc-avatarImg" %>

		<div class="twPc-divUser">
			<div class="twPc-divName">
				<p><%= current_user.name %></p>
			</div>
			<span>
				<%= link_to "oglej si profil", current_user %>
			</span>
		</div>
		<br/>

		<div class="twPc-divStats">
			<ul class="twPc-Arrange">
				<li class="twPc-ArrangeSizeFit">
					<p>
						<span class="twPc-StatLabel twPc-block">Objav</span>
						<span class="twPc-StatValue"><%= current_user.microposts.count %></span>
					</p>
				</li>
				<li class="twPc-ArrangeSizeFit">
					<p>
						<span class="twPc-StatLabel twPc-block">Sledeni</span>
						<span class="twPc-StatValue"><%= current_user.following.count %></span>
					</p>
				</li>
				<li class="twPc-ArrangeSizeFit">
					<p>
						<span class="twPc-StatLabel twPc-block">Sledilci</span>
						<span class="twPc-StatValue"><%= current_user.followers.count %></span>
					</p>
				</li>
			</ul>
		</div>
	</div>
</div>