config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  

  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2016 <a href="http://vido.si">Tvidter sample app</a>
    by <a href="http://vido.si/">Vid Jerčič</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Opis",   about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <li><a href="http://vido.si/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- new-->
<div class="navbar navbar-blue navbar-fixed-top">  
                    <div class="navbar-header">
                      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle</span>
                        <span class="icon-bar"></span>
          				<span class="icon-bar"></span>
          				<span class="icon-bar"></span>
                      </button>
                      <%= link_to "v", root_path, class: "navbar-brand logo" %>
                  	</div>
                  	<nav class="collapse navbar-collapse" role="navigation">
                    <ul class="nav navbar-nav">
                      <li>
                        <li><%= link_to "Tvidter", root_path, class: "navbar-brand" %></li>
                      </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right" id="userdrop">
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i></a>
                        <ul class="dropdown-menu">
                          <% if logged_in? %>
                            <li><%= link_to "Uporabniki", users_path %></li>
                            <li><%= link_to "Profil", current_user %></li>
                            <li><%= link_to "Nastavitve", edit_user_path(current_user) %></li>
                            <li>
                              <%= link_to "Odjava", logout_path, method: "delete" %>
                            </li>
                          <% else %>
                            <li><%= link_to "Prijava", login_path %></li>
                          <% end %>
                        </ul>
                      </li>
                    </ul>
                  	</nav>
                </div>

app/views/layouts/_shim.html.erb
 <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>